# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
