# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170123_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('publicado', 'Publicado'), ('expirado', 'Expirado')], default=0, max_length=10),
        ),
    ]
