# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170127_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
