# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
