# Generated by Django 2.2.4 on 2019-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(default='R$', max_length=5),
        ),
    ]
